/**
 * Feed Configuration for The Firehose
 * 
 * This file contains all CNCF project GitHub release feeds.
 * Feeds are organized by project maturity level (Graduated, Incubating, Sandbox).
 * 
 * Total: 161 projects (35 Graduated, 27 Incubating, 99 Sandbox)
 * 
 * Structure:
 * - url: GitHub Atom feed URL (required)
 * - project: Optional project name override (defaults to landscape match)
 */

export interface FeedConfig {
  url: string;
  project?: string;
}

/**
 * All CNCF project release feeds
 * Extracted from osmosfeed.yaml and filtered to GitHub releases only
 */
const feeds: FeedConfig[] = [
  // CNCF Graduated Projects
  { url: 'https://github.com/argoproj/argo-cd/releases.atom' },
  { url: 'https://github.com/cert-manager/cert-manager/releases.atom' },
  { url: 'https://github.com/cilium/cilium/releases.atom' },
  { url: 'https://github.com/cloudevents/spec/releases.atom' },
  { url: 'https://github.com/containerd/containerd/releases.atom' },
  { url: 'https://github.com/coredns/coredns/releases.atom' },
  { url: 'https://github.com/cri-o/cri-o/releases.atom' },
  { url: 'https://github.com/crossplane/crossplane/releases.atom' },
  { url: 'https://github.com/cubeFS/cubefs/releases.atom' },
  { url: 'https://github.com/dapr/dapr/releases.atom' },
  { url: 'https://github.com/dragonflyoss/dragonfly/releases.atom' },
  { url: 'https://github.com/envoyproxy/envoy/releases.atom' },
  { url: 'https://github.com/etcd-io/etcd/releases.atom' },
  { url: 'https://github.com/falcosecurity/falco/releases.atom' },
  { url: 'https://github.com/fluent/fluentd/releases.atom' },
  { url: 'https://github.com/fluxcd/flux2/releases.atom' },
  { url: 'https://github.com/goharbor/harbor/releases.atom' },
  { url: 'https://github.com/grpc/grpc/releases.atom' },
  { url: 'https://github.com/helm/helm/releases.atom' },
  { url: 'https://github.com/in-toto/in-toto/releases.atom' },
  { url: 'https://github.com/istio/istio/releases.atom' },
  { url: 'https://github.com/jaegertracing/jaeger/releases.atom' },
  { url: 'https://github.com/kedacore/keda/releases.atom' },
  { url: 'https://github.com/knative/serving/releases.atom' },
  { url: 'https://github.com/kubeedge/kubeedge/releases.atom' },
  { url: 'https://github.com/kubernetes/kubernetes/releases.atom' },
  { url: 'https://github.com/linkerd/linkerd2/releases.atom' },
  { url: 'https://github.com/open-policy-agent/opa/releases.atom' },
  { url: 'https://github.com/prometheus/prometheus/releases.atom' },
  { url: 'https://github.com/rook/rook/releases.atom' },
  { url: 'https://github.com/spiffe/spiffe/releases.atom' },
  { url: 'https://github.com/spiffe/spire/releases.atom' },
  { url: 'https://github.com/theupdateframework/python-tuf/releases.atom' },
  { url: 'https://github.com/tikv/tikv/releases.atom' },
  { url: 'https://github.com/vitessio/vitess/releases.atom' },
  
  // CNCF Incubating Projects
  { url: 'https://github.com/backstage/backstage/releases.atom' },
  { url: 'https://github.com/buildpacks/pack/releases.atom' },
  { url: 'https://github.com/chaos-mesh/chaos-mesh/releases.atom' },
  { url: 'https://github.com/cloud-custodian/cloud-custodian/releases.atom' },
  { url: 'https://github.com/containernetworking/cni/releases.atom' },
  { url: 'https://github.com/projectcontour/contour/releases.atom' },
  { url: 'https://github.com/cortexproject/cortex/releases.atom' },
  { url: 'https://github.com/emissary-ingress/emissary/releases.atom' },
  { url: 'https://github.com/karmada-io/karmada/releases.atom' },
  { url: 'https://github.com/keycloak/keycloak/releases.atom' },
  { url: 'https://github.com/kserve/kserve/releases.atom' },
  { url: 'https://github.com/kubevela/kubevela/releases.atom' },
  { url: 'https://github.com/kubevirt/kubevirt/releases.atom' },
  { url: 'https://github.com/kubeflow/kubeflow/releases.atom' },
  { url: 'https://github.com/kyverno/kyverno/releases.atom' },
  { url: 'https://github.com/litmuschaos/litmus/releases.atom' },
  { url: 'https://github.com/longhorn/longhorn/releases.atom' },
  { url: 'https://github.com/metal3-io/baremetal-operator/releases.atom' },
  { url: 'https://github.com/nats-io/nats-server/releases.atom' },
  { url: 'https://github.com/notaryproject/notary/releases.atom' },
  { url: 'https://github.com/open-feature/spec/releases.atom' },
  { url: 'https://github.com/openkruise/kruise/releases.atom' },
  { url: 'https://github.com/open-telemetry/opentelemetry-collector/releases.atom' },
  { url: 'https://github.com/operator-framework/operator-sdk/releases.atom' },
  { url: 'https://github.com/strimzi/strimzi-kafka-operator/releases.atom' },
  { url: 'https://github.com/thanos-io/thanos/releases.atom' },
  { url: 'https://github.com/volcano-sh/volcano/releases.atom' },
  
  // CNCF Sandbox Projects
  { url: 'https://github.com/AthenZ/athenz/releases.atom' },
  { url: 'https://github.com/NagiosEnterprises/nagioscore/releases.atom' },
  { url: 'https://github.com/Project-HAMi/HAMi/releases.atom' },
  { url: 'https://github.com/aeraki-mesh/aeraki/releases.atom' },
  { url: 'https://github.com/armadaproject/armada/releases.atom' },
  { url: 'https://github.com/bank-vaults/vault-operator/releases.atom' },
  { url: 'https://github.com/bank-vaults/vault-sdk/releases.atom' },
  { url: 'https://github.com/bpfman/bpfman-operator/releases.atom' },
  { url: 'https://github.com/cadence-workflow/cadence/releases.atom' },
  { url: 'https://github.com/carvel-dev/ytt/releases.atom' },
  { url: 'https://github.com/cdk8s-team/cdk8s/releases.atom' },
  { url: 'https://github.com/cedar-policy/cedar/releases.atom' },
  { url: 'https://github.com/chaosblade-io/chaosblade/releases.atom' },
  { url: 'https://github.com/clusternet/clusternet/releases.atom' },
  { url: 'https://github.com/clusterpedia-io/clusterpedia/releases.atom' },
  { url: 'https://github.com/confidential-containers/confidential-containers/releases.atom' },
  { url: 'https://github.com/connectrpc/connect-go/releases.atom' },
  { url: 'https://github.com/container2wasm/container2wasm/releases.atom' },
  { url: 'https://github.com/devfile/api/releases.atom' },
  { url: 'https://github.com/devspace-sh/devspace/releases.atom' },
  { url: 'https://github.com/distribution/distribution/releases.atom' },
  { url: 'https://github.com/emqx/emqx/releases.atom' },
  { url: 'https://github.com/eraser-dev/eraser/releases.atom' },
  { url: 'https://github.com/external-secrets/external-secrets/releases.atom' },
  { url: 'https://github.com/getporter/porter/releases.atom' },
  { url: 'https://github.com/getsops/sops/releases.atom' },
  { url: 'https://github.com/hexa-org/policy-orchestrator/releases.atom' },
  { url: 'https://github.com/hwameistor/hwameistor/releases.atom' },
  { url: 'https://github.com/hyperlight-dev/hyperlight/releases.atom' },
  { url: 'https://github.com/inclavare-containers/inclavare-containers/releases.atom' },
  { url: 'https://github.com/inspektor-gadget/inspektor-gadget/releases.atom' },
  { url: 'https://github.com/interlink-hq/interLink/releases.atom' },
  { url: 'https://github.com/k3s-io/k3s/releases.atom' },
  { url: 'https://github.com/k8gb-io/k8gb/releases.atom' },
  { url: 'https://github.com/k8sgpt-ai/k8sgpt/releases.atom' },
  { url: 'https://github.com/k8up-io/k8up/releases.atom' },
  { url: 'https://github.com/kairos-io/kairos/releases.atom' },
  { url: 'https://github.com/kaito-project/kaito/releases.atom' },
  { url: 'https://github.com/kcl-lang/kcl/releases.atom' },
  { url: 'https://github.com/kcp-dev/kcp/releases.atom' },
  { url: 'https://github.com/keylime/keylime/releases.atom' },
  { url: 'https://github.com/kgateway-dev/kgateway/releases.atom' },
  { url: 'https://github.com/kitops-ml/kitops/releases.atom' },
  { url: 'https://github.com/ko-build/ko/releases.atom' },
  { url: 'https://github.com/konveyor/operator/releases.atom' },
  { url: 'https://github.com/kptdev/kpt/releases.atom' },
  { url: 'https://github.com/kuasar-io/kuasar/releases.atom' },
  { url: 'https://github.com/kube-burner/kube-burner/releases.atom' },
  { url: 'https://github.com/kube-green/kube-green/releases.atom' },
  { url: 'https://github.com/kube-logging/logging-operator/releases.atom' },
  { url: 'https://github.com/kube-vip/kube-vip/releases.atom' },
  { url: 'https://github.com/kubedl-io/kubedl/releases.atom' },
  { url: 'https://github.com/kubefleet-dev/kubefleet/releases.atom' },
  { url: 'https://github.com/kubeovn/kube-ovn/releases.atom' },
  { url: 'https://github.com/kubernetes-sigs/headlamp/releases.atom' },
  { url: 'https://github.com/kubestellar/kubestellar/releases.atom' },
  { url: 'https://github.com/kubewarden/community/releases.atom' },
  { url: 'https://github.com/kubewarden/kubewarden-controller/releases.atom' },
  { url: 'https://github.com/kubewarden/kwctl/releases.atom' },
  { url: 'https://github.com/kumahq/kuma/releases.atom' },
  { url: 'https://github.com/lxc/lxd/releases.atom' },
  { url: 'https://github.com/meshery/meshery/releases.atom' },
  { url: 'https://github.com/metallb/metallb/releases.atom' },
  { url: 'https://github.com/microcks/microcks/releases.atom' },
  { url: 'https://github.com/modelpack/model-spec/releases.atom' },
  { url: 'https://github.com/networkservicemesh/api/releases.atom' },
  { url: 'https://github.com/oauth2-proxy/manifests/releases.atom' },
  { url: 'https://github.com/opcr-io/policy/releases.atom' },
  { url: 'https://github.com/open-cluster-management-io/ocm/releases.atom' },
  { url: 'https://github.com/openGemini/openGemini/releases.atom' },
  { url: 'https://github.com/openebs/openebs/releases.atom' },
  { url: 'https://github.com/openyurtio/openyurt/releases.atom' },
  { url: 'https://github.com/oscal-compass/compliance-trestle-agile-authoring/releases.atom' },
  { url: 'https://github.com/oscal-compass/compliance-trestle-demos/releases.atom' },
  { url: 'https://github.com/ovn-kubernetes/ovn-kubernetes/releases.atom' },
  { url: 'https://github.com/oxia-db/oxia-client-java/releases.atom' },
  { url: 'https://github.com/parallaxsecond/parsec/releases.atom' },
  { url: 'https://github.com/pipe-cd/pipecd/releases.atom' },
  { url: 'https://github.com/pipelineai/pipeline/releases.atom' },
  { url: 'https://github.com/piraeusdatastore/piraeus-operator/releases.atom' },
  { url: 'https://github.com/pixie-io/pixie/releases.atom' },
  { url: 'https://github.com/podman-desktop/podman-desktop/releases.atom' },
  { url: 'https://github.com/project-akri/akri/releases.atom' },
  { url: 'https://github.com/project-copacetic/copacetic/releases.atom' },
  { url: 'https://github.com/project-dalec/dalec/releases.atom' },
  { url: 'https://github.com/project-zot/zot/releases.atom' },
  { url: 'https://github.com/runmedev/runme/releases.atom' },
  { url: 'https://github.com/schemahero/schemahero/releases.atom' },
  { url: 'https://github.com/serverless-devs/serverless-devs/releases.atom' },
  { url: 'https://github.com/serverlessworkflow/specification/releases.atom' },
  { url: 'https://github.com/slimtoolkit/slim/releases.atom' },
  { url: 'https://github.com/submariner-io/submariner/releases.atom' },
  { url: 'https://github.com/sustainable-computing-io/kepler/releases.atom' },
  { url: 'https://github.com/telepresenceio/telepresence/releases.atom' },
  { url: 'https://github.com/v6d-io/v6d/releases.atom' },
  { url: 'https://github.com/virtual-kubelet/virtual-kubelet/releases.atom' },
  { url: 'https://github.com/xregistry/server/releases.atom' },
  { url: 'https://github.com/xregistry/xregistry.github.io/releases.atom' },
  { url: 'https://github.com/youki-dev/youki/releases.atom' },
];

export default feeds;
