// DISABLED: Content Layer now replaced with JSON import in src/pages/index.astro
// This file is kept for reference but collections are empty
// The old feedLoader has been replaced by the Go backend generating src/data/releases.json

// import { defineCollection } from 'astro:content';
// import { feedLoader } from '../lib/feed-loader';
// import { FeedEntrySchema } from '../lib/schemas';
// import feeds from '../config/feeds';

/**
 * Empty collections export - Content Layer disabled
 * Data now comes from src/data/releases.json generated by Go backend
 */
export const collections = {};
